sudo: required
env:
  global:
    - WASM_LLVM_BIN=/usr/bin
    - DOCKER_IMG=yglukhov/debian-stretch.base.wasm.nim
services:
  - docker
before_install:
  - docker pull $DOCKER_IMG
script:
  - docker run -v "$(pwd):/project" -w /project $DOCKER_IMG nim --version
  - docker run -e WASM_LLVM_BIN -v "$(pwd):/project" -w /project $DOCKER_IMG nimble test

